FROM ruby:2.5
RUN apt-get update && apt-get install -y \
      build-essential \
      libpq-dev \
      nodejs \
      postgresql-client \
      yarn
ENV APP_HOME /myproject
WORKDIR $APP_HOME
COPY Gemfile Gemfile.lock $APP_HOME
RUN bundle install
COPY . .
RUN rails assets:precompile
CMD ["rails","s"]